resources:
  repositories:
    - repository: templates
      type: github
      name: SCRT-HQ/AzurePipelineTemplates
      endpoint: Github

trigger:
  branches:
    include:
      - master
      - main
  paths:
    include:
      - PowerShell/ModuleBuildTest/*

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  always: true
  branches:
    include:
      - main

stages:
- stage: Preview
  dependsOn: []
  jobs:
    - job: preview
      displayName: Build Test Push
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: BuildTestDeployDocker/azure-pipelines.yml@templates
          parameters:
              containerRegistry: DockerHub
              repository: scrthq/powershell
              dockerFile: PowerShell/ModuleBuildTest/Preview.Dockerfile
              testFile: PowerShell/ModuleBuildTest/TestPreview.Dockerfile
              tag: preview-buildtest-ubu-2004

- stage: PreviewNoEntrypoint
  displayName: Preview (No Entrypoint)
  dependsOn: []
  jobs:
    - job: previewNoEntrypoint
      displayName: Build Test Push
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: BuildTestDeployDocker/azure-pipelines.yml@templates
          parameters:
              containerRegistry: DockerHub
              repository: scrthq/powershell
              dockerFile: PowerShell/ModuleBuildTest/Preview-NoEntryPoint.Dockerfile
              testFile: PowerShell/ModuleBuildTest/TestPreview-NoEntryPoint.Dockerfile
              tag: preview-noentrypoint-buildtest-ubu-2004

- stage: Latest
  dependsOn: []
  jobs:
    - job: latest
      displayName: Build Test Push
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: BuildTestDeployDocker/azure-pipelines.yml@templates
          parameters:
              containerRegistry: DockerHub
              repository: scrthq/powershell
              dockerFile: PowerShell/ModuleBuildTest/Latest.Dockerfile
              testFile: PowerShell/ModuleBuildTest/TestLatest.Dockerfile
              tag: latest-buildtest-ubu-2004
